services:
  ecs_dev_php_template:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    container_name: ecs_dev_php_template
    hostname: ecs_dev_php_template
    shm_size: '4gb'
    ports:
      - 9003:9003
    volumes:
      - $PWD/:/workspace:cached
      - $PWD/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    environment:
      GIT_AUTHOR_NAME: ${GIT_USERNAME}
      GIT_COMMITTER_NAME: ${GIT_USERNAME}
      GIT_AUTHOR_EMAIL: ${GIT_EMAIL_ADDRESS}
      GIT_COMMITTER_EMAIL: ${GIT_EMAIL_ADDRESS}
      TZ: Asia/Tokyo
    tty: true
