services:
  ecs_dev_php_template:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_EMAIL_ADDRESS: ${GIT_EMAIL_ADDRESS}
    container_name: ecs_dev_php_template
    hostname: ecs_dev_php_template
    shm_size: '4gb'
    ports:
      - 9003:9003
    volumes:
      - $PWD/:/workspace:cached
      - $PWD/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    environment:
      TZ: Asia/Tokyo
    tty: true
